CREATE DATABASE IF NOT EXISTS idruide;

USE idruide;

CREATE TABLE if NOT EXISTS annuaire (
       Identifiant_de_l_etablissement VARCHAR(80),
       Nom_etablissement VARCHAR(80),
       Type_etablissement VARCHAR(80),
       Statut_public_prive VARCHAR(80),
       Adresse_1 VARCHAR(80),
       Adresse_2 VARCHAR(80),
       Adresse_3 VARCHAR(80),
       Code_postal VARCHAR(80),
       Code_commune VARCHAR(80),
       Nom_commune VARCHAR(80),
       Code_departement VARCHAR(80),
       Code_academie VARCHAR(80),
       Code_region VARCHAR(80),
       Ecolde_maternelle VARCHAR(80),
       Ecole_elementaire VARCHAR(80),
       Voie_generale VARCHAR(80),
       Voie_technologique VARCHAR(80),
       Voie_professionnelle VARCHAR(80),
       Telephone VARCHAR(80),
       Fax VARCHAR(80),
       Web VARCHAR(80),
       Mail VARCHAR(80),
       Restauration VARCHAR(80),
       Hebergement VARCHAR(80),
       ULIS VARCHAR(80),
       Apprentissage VARCHAR(80),
       Segpa VARCHAR(80),
       Section_arts VARCHAR(80),
       Section_cinema VARCHAR(80),
       Section_theatre VARCHAR(80),
       Section_sport VARCHAR(80),
       Section_internationale VARCHAR(80),
       Section_europeenne VARCHAR(80),
       Lycee_Agricole VARCHAR(80),
       Lycee_militaire VARCHAR(80),
       Lycee_des_metiers VARCHAR(80),
       Post_BAC VARCHAR(80),
       Appartenance_Education_Prioritaire VARCHAR(80),
       GRETA VARCHAR(80),
       SIREN_SIRET VARCHAR(80),
       Nombre_d_eleves VARCHAR(80),
       Fiche_onisep VARCHAR(80),
       position VARCHAR(80),
       Type_contrat_prive VARCHAR(80),
       Libelle_departement VARCHAR(80),
       Libelle_academie VARCHAR(80),
       Libelle_region VARCHAR(80),
       coordonnee_X VARCHAR(80),
       coordonnee_Y VARCHAR(80),
       epsg VARCHAR(80),
       nom_circonscription VARCHAR(80),
       latitude VARCHAR(80),
       longitude VARCHAR(80),
       precision_localisation VARCHAR(80),
       date_ouverture VARCHAR(80),
       date_maj_ligne VARCHAR(80),
       etat VARCHAR(80),
       ministere_tutelle VARCHAR(80),
       etablissement_multi_lignes VARCHAR(80),
       rpi_concentre VARCHAR(80),
       rpi_disperse VARCHAR(80),
       code_nature VARCHAR(80),
       libelle_nature VARCHAR(80),
       Code_type_contrat_prive VARCHAR(80),
       PIAL VARCHAR(80),
       etablissement_mere VARCHAR(80),
       type_rattachement_etablissement_mere VARCHAR(80),
       code_bassin_formation VARCHAR(80),
       libelle_bassin_formation VARCHAR(80),
       id INT NOT NULL KEY AUTO_INCREMENT
);

